language: objective-c
osx_image: xcode8.2
sudo: false
rvm:
  - 2.3

cache:
  - bundler
  - cocoapods

env:
  global:
    - WORKSPACE="Drrrible.xcworkspace"
    - IOS_SDK="iphonesimulator10.2"
    - IOS_DESTINATION="platform=iOS Simulator,name=iPhone 7,OS=10.2"
  matrix:
    - SCHEME="Drrrible"        SDK="$IOS_SDK"      ACTION="test"

install:
  - bundle install --deployment
  - bundle exec pod --version
  - bundle exec pod repo update --silent
  - bundle exec pod install

before_script:
  - fastlane snapshot reset_simulators --force

script:
  - set -o pipefail && xcodebuild clean $ACTION -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$IOS_DESTINATION" -configuration Debug CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty -c
